### PR TITLE
New logos for open data services and public data lab

### PR DESCRIPTION
**Pull request by timgdavies**

### CODE REVIEW

**Comment by timgdavies** [comment]
@jwyg @StephenAbbott Do either of you have permissions to merge this change? 

It looks to me like this might then need a command run locally to build the gh-pages branch before it goes to the live site?

**Comment by StephenAbbott** [comment]
@smth Would you be able to merge this change for the OD4TJ website to update/add a couple of logos? Many thanks

**Comment by smth** [comment]
Done, and deployed.

**Comment by StephenAbbott** [comment]
Thanks @smth!

**Pull request merged**
